-- Buffer control
vim.keymap.set("n", "<leader>v", "<cmd>:vsplit<cr>", { noremap = true, silent = true, desc = "Split vertically" })
vim.keymap.set("n", "<leader>h", "<cmd>:split<cr>", { noremap = true, silent = true, desc = "Split horizontally" })
vim.keymap.set("n", "<leader>q", "<cmd>:bd<cr>", { noremap = true, silent = true, desc = "Close buffer" })
vim.keymap.set("n", "<S-Left>", "<cmd>:bp<cr>", { noremap = true, silent = true, desc = "Move to the previous buffer" })
vim.keymap.set("n", "<S-Right>", "<cmd>:bn<cr>", { noremap = true, silent = true, desc = "Move to the next buffer" })
vim.keymap.set("n", "<C-S-Up>", "<cmd>:wincmd k<cr>", { noremap = true, silent = true, desc = "Move to the window on the top" })
vim.keymap.set("n", "<C-S-Down>", "<cmd>:wincmd j<cr>", { noremap = true, silent = true, desc = "Move to the window on the bottom" })
vim.keymap.set("n", "<C-S-Left>", "<cmd>:wincmd h<cr>", { noremap = true, silent = true, desc = "Move to the window on the left" })
vim.keymap.set("n", "<C-S-Right>", "<cmd>:wincmd l<cr>", { noremap = true, silent = true, desc = "Move to the window on the right" })
-- vim.keymap.set("n", "<C-S-Left>", "<cmd>:tabprevious<cr>", { noremap = true, silent = true, desc = "Move to the previous tab" })
-- vim.keymap.set("n", "<C-S-Right>", "<cmd>:tabnext<cr>", { noremap = true, silent = true, desc = "Move to the next tab" })